name: Publish

on:
  push:
    tags: 
      - 1.*
jobs:
  publish:
    name: Publish VS Code Extension
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Tag
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.push.ref }}
    
    - name: Use Node.js 16.*
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    
    - run: npm i
    
    - name: Publish extension
      uses: sigma/vsce-publish-action@v0.0.2
      with:
        vsce_token: ${{ secrets.VSCE_TOKEN }}  
